[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_RUNTIME_ENV = "production"

# Handle 404s properly in the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 